apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-init
spec:
  template:
    spec:
      containers:
        - name: airflow-init
          image: apache/airflow:2.7.1
          envFrom:
            - configMapRef:
                name: weather-etl-config
          command:
            - "/bin/bash"
            - "-c"
            - |
              airflow db init && \
              airflow users create \
                --username admin \
                --password admin \
                --firstname admin \
                --lastname admin \
                --role Admin \
                --email admin@example.com
      restartPolicy: OnFailure
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
        - name: airflow-webserver
          image: apache/airflow:2.7.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: weather-etl-config
          command:
            - "/bin/bash"
            - "-c"
            - "airflow webserver"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
        - name: airflow-scheduler
          image: apache/airflow:2.7.1
          envFrom:
            - configMapRef:
                name: weather-etl-config
          command:
            - "/bin/bash"
            - "-c"
            - "airflow scheduler"
          volumeMounts:
            - name: dags-volume
              mountPath: /opt/airflow/dags
      volumes:
        - name: dags-volume
          configMap:
            name: airflow-dags
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
spec:
  type: LoadBalancer
  selector:
    app: airflow-webserver
  ports:
    - port: 8080
      targetPort: 8080
